### ISSUE TITLE
Font Size too bigger with some devices

### ISSUE THREAD

**Issue by briantofu** [nirsky/react-native-size-matters#42] opened 2020-07-03 02:56 UTC
Hi. Just want to raise this issue that some devices is too big scaling the font size. I've been trying to some devices and it's all okay for scaling. What causes the issue?

Issue from iPhone 8 Plus
<img width="598" alt="Screen Shot 2020-07-03 at 10 54 42 AM" src="https://user-images.githubusercontent.com/28759807/86426968-9c2a3580-bd1b-11ea-9945-ddcd15b70593.png">
Other Devices were okay tho (Iphone SE, iPhone 11, Android Google Pixel 3)
<img width="902" alt="Screen Shot 2020-07-03 at 10 55 24 AM" src="https://user-images.githubusercontent.com/28759807/86427002-b5cb7d00-bd1b-11ea-9431-96792cc61540.png">

Thanks!

**Comment by nirsky** [comment] 2020-07-05 08:56
Hey, I suggest one of the following: 
* Adjust the scaling function used on the font.
* Apply a scaling function on the text container as well.
* Make the container size dynamic (don't set fixed width/height).

Also, I don't consider this as an issue in this lib, but rather a wrong usage, so I'm gonna close this issue.
Feel free to let me know how this worked for you (even though the issue is closed).

**Closed by nirsky** 2020-07-05 08:56 UTC
