### ISSUE TITLE
Jest Testing Fails

### ISSUE THREAD

**Issue by parsable-mhalum** [nirsky/react-native-size-matters#61] opened 2021-02-12 06:29 UTC
I'm using your library for styling and when I'm updating my snapshots for jest react-native-size-matters keeps on failing the test here is the screen shot of the error.

![image](https://user-images.githubusercontent.com/77645198/107737163-bf4fa580-6d3e-11eb-82ca-4ec09616bc5f.png)

**Comment by nirsky** [comment] 2021-02-15 07:55
Hey @parsable-mhalum,
I need some more information to try and reproduce this:
- react-native-size-matters version
- react-native version
- jest version
- jest config
- any babel config (or similar tool if something else is used)

**Comment by parsable-mhalum** [comment] 2021-02-15 13:15
hi @nirsky,

Here are the information that you need:

"react-native-size-matters": "^0.4.0",
"react-native": "0.63.4",
"jest": "^25.1.0",

Babel Config:
![image](https://user-images.githubusercontent.com/77645198/107950764-2df86180-6fd2-11eb-8735-c3ec6bce4d0c.png)

Test Example:
![image](https://user-images.githubusercontent.com/77645198/107950802-3d77aa80-6fd2-11eb-8155-b21e399f59e7.png)

**Comment by nirsky** [comment] 2021-03-29 12:22
Seems like the issue is related to the fact that `react-native-size-matters` is shipped uncompiled (common for react-native libs).  
Related StackOverflow answer - https://stackoverflow.com/a/55803188/2546475
Jest offers a solution - https://jestjs.io/docs/tutorial-react-native#transformignorepatterns-customization

I was able to get it work with the following jest config:
```json
"jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(@react-native|react-native|react-native-size-matters)/)"
    ]
}
```

Let me know if this works for you.
I'll also consider shipping this lib pre-complied.

**Comment by nirsky** [comment] 2021-04-01 13:25
I had issues compiling this project to commonJS due to `babel-plugin-dotenv-import` not working in commonJS.  
So I'm gonna leave the solution as-is and close this issue.

**Closed by nirsky** 2021-04-01 13:25 UTC

**Comment by adeadavid** [comment] 2023-04-12 01:39
> Seems like the issue is related to the fact that `react-native-size-matters` is shipped uncompiled (common for react-native libs). Related StackOverflow answer - https://stackoverflow.com/a/55803188/2546475 Jest offers a solution - https://jestjs.io/docs/tutorial-react-native#transformignorepatterns-customization
> 
> I was able to get it work with the following jest config:
> 
> ```json
> "jest": {
>     "preset": "react-native",
>     "transformIgnorePatterns": [
>       "node_modules/(?!(@react-native|react-native|react-native-size-matters)/)"
>     ]
> }
> ```
> 
> Let me know if this works for you. I'll also consider shipping this lib pre-complied.

This doesn't resolve the issue, I'm still getting the error

**Comment by DenisDov** [comment] 2024-06-25 10:59
i use this `jest.config.js` for patched `react-native-size-matters/extend`, and it's working now for me:
```js
/** @type {import('jest').Config} */
const config = {
  verbose: true,
  preset: "react-native",
  setupFiles: ["<rootDir>/jest.setup.js"],
  setupFilesAfterEnv: ["@testing-library/react-native/extend-expect"],
  transformIgnorePatterns: [
    "node_modules/(?!(@react-native|react-native|react-native-size-matters(?!/extend)))/",
  ],
};

module.exports = config;


```
