### ISSUE TITLE
(0 , _ScaledSheet.default) is not a function  

### ISSUE THREAD

**Issue by jindong5210** [nirsky/react-native-size-matters#32] opened 2019-09-19 02:18 UTC
Hello
Wierd error accurs. when I import extend lib.

.env
```
SIZE_MATTERS_BASE_WIDTH=750
SIZE_MATTERS_BASE_HEIGHT=1336
```

app.js
```
import { ScaledSheet } from 'react-native-size-matters/extend';
```

-------------------

```
(0 , _ScaledSheet.default) is not a function

<unknown>
    extend.js:4:46
loadModuleImplementation
    require.js:302:4
guardedLoadModule
    require.js:203:11
metroRequire
    require.js:122:6
<unknown>
    App.js:9
loadModuleImplementation
    require.js:302:4
guardedLoadModule
    require.js:203:11
metroRequire
    require.js:122:6
<unknown>
    index.js:6
loadModuleImplementation
    require.js:302:4
```

**Comment by jindong5210** [comment] 2019-09-19 02:48
```
"react": "16.8.6",
"react-native": "0.60.5",
```

**Comment by jindong5210** [comment] 2019-09-19 05:19
It works fine when I copy it to local folder.

**Comment by nirsky** [comment] 2019-09-19 06:44
Will it work without the `extend`? (`import { ScaledSheet } from 'react-native-size-matters';`).
What version of react-native-size-matters are you using?

**Comment by jindong5210** [comment] 2019-09-19 08:36
It works fine without `extend`

The version is:
```
"react-native-size-matters": "^0.2.1",
```

**Comment by daibergm** [comment] 2020-02-13 14:52
@jindong5210 Maybe you can try to update the lib to v0.3.0, because i work with that version, and extend functionality work fine

**Comment by nirsky** [comment] 2020-02-16 09:26
Gonna close this for now as it doesn't seem to reproduce for others.

**Closed by nirsky** 2020-02-16 09:26 UTC
